Cypress test automation
GSA/usagov-benefits-eligibility pull request #833
Opened 2023-05-17 17:55 UTC by nehemiah-abuga

## PR Summary

In this PR cypress automated tests have been added with the capability to run on CI/CD
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.

## Steps to Validate
- [ ] Checkout the branch on your local
-  [ ] run ``` npm install ``` to add the dependencies
- [ ] run ``` npm run cypress:run ``` and validate 5 headers tests pass
- [ ] run ```npm run cypress:open ``` and select E2E testing and browser of choice. Run the header tests
- [ ] In github, navigate to https://github.com/GSA/usagov-benefits-eligibility/actions/workflows/cypress.yml
- [ ] Run you tests again the cypress-test-automation branch
- [ ] Verify all the 5 headers tests pass

I have verified a success run 
https://github.com/GSA/usagov-benefits-eligibility/actions/runs/5006183114/jobs/8971111047

2023-05-18 20:48 UTC, FatmaBakir approved these changes
Approved!

2023-05-23 19:30 UTC, nehemiah-abuga commented
@scottqueen-bixal  - please review the changes

2023-05-24 13:52 UTC, scottqueen-bixal commented
There still seems to be an additional workflow, let's remove the one we don't use
<img width="343" alt="Screenshot 2023-05-24 at 9 48 52 AM" src="https://github.com/GSA/usagov-benefits-eligibility/assets/37077057/2d8b1b9c-614e-45a4-8394-82c8ba1a590c">

2023-05-24 15:05 UTC, scottqueen-bixal requested changes

2023-05-24 15:21 UTC, nehemiah-abuga commented
> 



> There still seems to be an additional workflow, let's remove the one we don't use

> This will be removed once we merge to main

2023-05-24 17:00 UTC, scottqueen-bixal requested changes

2023-05-24 17:00 UTC, scottqueen-bixal commented on package.json
> +    "nuxt-i18n": "^6.28.1",
this shouldn't be in here

please remove, and rebuild package.json

2023-05-24 19:56 UTC, scottqueen-bixal approved these changes

2023-05-24 20:01 UTC, merged