add links tests
GSA/usagov-benefits-eligibility pull request #890
Opened 2023-06-14 17:16 UTC by nehemiah-abuga

## PR Summary

The PR is add tests to validate 2XX and #XX status response for the various links within 

Death of a loved one English and Spanish page
Disability English and Spanish page
Retirement English and Spanish page

## Related Github Issue

- task #(883)

## Type of change

- [ ] Task
- [ ] New feature - Test Automation

## Detailed Testing steps

Run ```npm run cypress:run_chrome ``` and verify all tests pass including the added links tests
Run ```npx cypress open``` and verify the links tests pass

2023-06-15 14:13 UTC, scottqueen-bixal requested changes

2023-06-15 18:54 UTC, nehemiah-abuga commented on cypress/e2e/ui/links.cy.js
> +          failOnStatusCode: false,
I have removed failOnStatusCode. Note there are test failing because the URLs needs to be updated

2023-06-15 21:27 UTC, nehemiah-abuga commented
@scottqueen-bixal - I have made the updates

2023-06-21 15:36 UTC, scottqueen-bixal approved these changes

2023-06-21 15:37 UTC, scottqueen-bixal commented
let's hold off on putting this in upstream until this ticket is completed https://github.com/orgs/GSA/projects/48/views/10?pane=issue&itemId=30816804

just so we don't have failing tests on all the other work coming in.

2023-06-27 14:19 UTC, scottqueen-bixal requested changes

2023-06-27 14:19 UTC, scottqueen-bixal commented on cypress/e2e/ui/links.cy.js
> +const sitePages = require("../../fixtures/site-pages.json")
Replace with import

2023-06-27 17:55 UTC, scottqueen-bixal approved these changes

2023-06-27 17:58 UTC, scottqueen-bixal commented
> let's hold off on putting this in upstream until this ticket is completed https://github.com/orgs/GSA/projects/48/views/10?pane=issue&itemId=30816804
> 
> just so we don't have failing tests on all the other work coming in.

Deciding to move forward based on the recommendation that 

> ....since from QA it is done we can merge into main because the code is doing what it is supposed to do...able to catch the issues

2023-06-27 17:58 UTC, merged