footer tests
GSA/usagov-benefits-eligibility pull request #896
Opened 2023-06-21 16:30 UTC by nehemiah-abuga

## PR Summary

This PR is to add footer tests on Spanish and English Pages

## Related Github Issue

- fixes #(887)

## Type of change

- [ ] Task
- [ ] New feature

## Detailed Testing steps
- [ ] Pull branch
- [ ] start local
- [ ] run ```npm run cypress:run_chrome```
- [ ] Verify ```footer.cy.js``` tests are passing

##Note 
Defect will need to be resolved for footer tests on spanish pages to pass

https://github.com/GSA/usagov-benefits-eligibility/issues/895

2023-06-21 20:03 UTC, scottqueen-bixal requested changes

2023-06-23 21:16 UTC, nehemiah-abuga commented on cypress/e2e/ui/footer.cy.js
> +  sitePages.forEach((sitePage) => {
Testing all routes as per discussion

2023-06-27 03:08 UTC, nehemiah-abuga commented on cypress/e2e/ui/footer.cy.js
> +const sitePages = require("../../fixtures/site-pages.json")
Changes have been made to use imports instead of require

2023-06-27 13:28 UTC, scottqueen-bixal approved these changes

2023-06-27 13:32 UTC, merged